---
- name: Modify users
  user:
    name: "{{ item.username }}"
    update_password: always
    password: "{{ item.password | string | password_hash('sha512') }}"
    state: present
  loop: "{{ users_to_modify }}"

